- name: add repo
  command: rpm -ih http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm creates=/etc/yum.repos.d/mysql-community.repo

- name: install mysql-community-server
  yum: name=mysql-community-server state=installed

- name: install MySQL-python for ansible mysql_user module
  yum: name=MySQL-python state=installed

- name: generate server-id
  shell:
    hostname -I | sed -e 's/ /n/' | grep -v '^$' | tail -1 | awk -F. '{ print $3 * 256 + $4 }'
  register: mysql_server_id

#- name: Copy the my.cnf
#  template: src=my.cnf.j2 dest=/etc/my.cnf
#  notify:
#    - restart mysqld

#- name: start server
#  service: name=mysqld state=started enabled=yes

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_db_pass }}
  with_items:
   - "{{ ansible_hostname }}"
   - 127.0.0.1
   - ::1
   - localhost
  when: ansible_hostname != 'localhost'

- name: Copy .my.cnf file with root password credential
  template: src=.my.cnf.j2 dest=~/.my.cnf mode=0600



#- name: save-mysql-tmp-password.sh
#  script: files/save-mysql-tmp-password.sh creates=/root/.tmp.my.cnf
#
#- name: set new password
#  script: files/change-root-password.sh creates=/root/.my.cnf

#- name: create new user
#  shell: mysql -e "GRANT ALL ON *.* TO vagrant IDENTIFIED BY 'FooBar12345@' "


#- name: Create the replication users
#  mysql_user: name={{ item }}  host="%" password={{ item.pass|default("MyNewPass4@") }}
#                priv=*.*:"REPLICATION SLAVE" state=present
#  with_items: mysql_repl_user
#  when: repl == 'master'

# TODO register: last_changed
#- name: restart mysql
#  service: name=mysql state=restarted
#  when: last_result.changed

#- name: create replication user
#  mysql_user:
#    name={{ mysql_repl_user }}
#    password={{ mysql_repl_pass }}
#    host=192.168.33.32
#    priv=*.*:"REPLICATION SLAVE"
#  when: repl == 'master'
#
#- name: start replication
#  mysql_replication:
#    mode=changemaster
#    master_host=192.168.33.31
#    master_user={{ mysql_repl_user }}
#    master_password={{ mysql_repl_pass }}
#  when: repl == 'slave'

