- hosts: db-servers
  sudo: true
  user: vagrant
  vars:
    items:
      - "hello world!"
      - "I love cats"
      - "I love dogs"

  tasks:
    - name: "echo list item"
      command: echo {{item}}
      with_items: items
